# Generated by Django 5.2.6 on 2025-09-19 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadegradecore', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ResultSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('faculty', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('years_of_study', models.PositiveSmallIntegerField(default=4)),
                ('semesters_per_year', models.PositiveSmallIntegerField(default=2)),
                ('entry_year', models.CharField(help_text='e.g. 2021/2022', max_length=20)),
                ('mode', models.CharField(choices=[('zeros', 'All zeros (Build up)'), ('available', 'Based on availability')], default='zeros', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='acadegradecore.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('credit_unit', models.PositiveSmallIntegerField(default=0)),
                ('incourse', models.PositiveSmallIntegerField(default=0)),
                ('exam', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='acadegradecore.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('year_label', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='acadegradecore.resultsheet')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('sheet', 'index')},
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='acadegradecore.year'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'index')},
        ),
    ]
